"""The menu bar app. A **separate process** from the
display agent.

Run: `display/.venv/bin/python3 ui/menubar.py`

This file is the AppKit shell and nothing else. Every decision it makes —
which state to show, whether the heartbeat is stale, how to truncate a
label, what the next command file should contain — lives in
`menubar_state.py`, which has no AppKit in it and is where the tests are.
What is left here is the part that can only be verified by looking at a
real menu bar: an `NSStatusItem`, a menu, a timer, and the code that
turns a decision into a `setTitle_` call.

**The two processes never write each other's files**. This one
writes `~/.viewlab/state/command.json` and reads
`~/.viewlab/state/status.json`; the display does exactly the reverse.
There is no other channel between them — no sockets, no notifications,
no shared memory — which is what makes "force-quit the UI and the
pictures keep rotating" true by construction rather than by care.

**Conventions this file follows, each for a reason already paid for:**

- `@objc.python_method` on every private helper. A plain snake_case
  method on an `NSObject` subclass is exported to the Objective-C
  runtime as a selector, and one of them has already collided with an
  AppKit selector in this project and cost a debugging session.
- A broad `try/except` around the body of **every** selector AppKit
  calls — timer callbacks and menu actions alike. An exception escaping
  an NSTimer selector kills the run loop; an exception escaping a menu
  action lands in AppKit's own dispatch and is at best logged somewhere
  nobody looks. The display agent has carried this rule since Phase 2.
- Reads never raise, writes are atomic write-then-rename (via
  `control.write_control` / `atomic_io`).
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
import traceback
from pathlib import Path

import AppKit
import objc

from display import control, paths, single_instance
from display.config_store import read_json_object
from ui import first_run_state as fr
from ui import menubar_state as ms

#: How often the UI re-reads `status.json`. Fast enough that the
#: transient label (a ~3s hold) cannot be missed entirely and that
#: a command's effect appears to land promptly, slow enough that this is
#: a stat call and a small JSON parse a couple of times a second rather
#: than the display's own 4Hz. The display is the real-time end of this
#: relationship; the menu bar is not.
POLL_INTERVAL_S = 0.4

#: Asset, generated by `packaging/make_menubar_template.py`.
#:
#: Resolved through `paths` rather than from `__file__`, because
#: `__file__` inside the bundle points into `Contents/Resources/lib/
#: python3NN.zip` and its `.parent.parent / "packaging"` is a directory
#: that does not exist — the icon would silently fail to load and the
#: status item would come up bare. A *function*, not a constant, so the
#: resolution happens after `sys.frozen` is set rather than at import.

#: The LaunchAgent label this UI drives.
#:
#: Deliberately the *pre-existing source-tree* one (the already
#: installed label stays as it is, only the shipped one changes), because
#: Step 2's job was to drive the display that is actually running on the
#: development machine.
#:
#: RELEASE BLOCKER, open at Step 6. For a packaged install the correct
#: value is `paths.DISPLAY_AGENT_LABEL` (`dev.viewlab.imageview.display`):
#: no other machine has the development agent, so a shipped build points
#: the Restart and Open-at-login controls at a label that does not exist
#: there. This constant was introduced as transitional but never given
#: a removal step. Switching it is a live behaviour change on the
#: development machine, so it is an owner decision, not a sweep.
DISPLAY_AGENT_LABEL = paths.DISPLAY_AGENT_LABEL


def agent_plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{DISPLAY_AGENT_LABEL}.plist"


class MenuBarController(AppKit.NSObject):
    """Owns the status item, the menu, and the one poll timer.

    An `NSObject` subclass because AppKit needs a target for the timer
    and for every menu action. Constructed with `alloc().init()`; the
    real setup is in `start`, so that a failure to build the status item
    is a logged error rather than an exception thrown out of `init`.
    """

    def init(self):
        self = objc.super(MenuBarController, self).init()
        if self is None:
            return None
        self._status_item = None
        self._menu = None
        self._items = {}
        self._timer = None
        self._titles = ms.TitleTracker()
        self._state = ms.State.NOT_SHOWING
        self._status = ms.Status()
        self._needs_setup = False
        self._text_region_width = 0.0
        # The open calibration window, or None. Held here rather
        # than on the app object because the menu's enabled-state depends
        # on it, and because nothing else retains it — a
        # CalibrateController collected out from under its own key
        # monitor takes both its windows with it.
        self._calibrate = None
        # The open settings window, or None. Held for the same
        # reason `_calibrate` is: nothing else retains it, and the menu's
        # enabled-state depends on whether one is already open.
        self._settings = None
        # The open first-run flow, or None. Same reasoning as the
        # two above.
        self._first_run = None
        return self

    # -- setup ----------------------------------------------------------

    @objc.python_method
    def start(self) -> None:
        bar = AppKit.NSStatusBar.systemStatusBar()
        self._status_item = bar.statusItemWithLength_(
            AppKit.NSVariableStatusItemLength
        )
        self._install_image()
        self._build_menu()
        self._status_item.setMenu_(self._menu)
        # Refresh once synchronously so the first thing drawn is already
        # correct -- otherwise the status item appears with a stale
        # "Not showing pictures" for up to POLL_INTERVAL_S even when the
        # display is running fine, which is exactly the misleading state
        # the precedence list is ordered to avoid.
        self._refresh()
        self._timer = AppKit.NSTimer.scheduledTimerWithTimeInterval_target_selector_userInfo_repeats_(
            POLL_INTERVAL_S, self, "pollTick:", None, True
        )
        # The flow opens by itself on a config that has never been
        # set up. `_refresh` has just computed `_needs_setup` from the
        # same `setup_needed` the menu title uses, so the window and the
        # `Setup needed` title can never disagree.
        #
        # Deferred to the next run-loop pass rather than called here: the
        # status item is not yet installed in the menu bar at this point,
        # and opening a window that calls `activateIgnoringOtherApps_`
        # before it is would leave an accessory app with a key window and
        # no visible status item behind it.
        if self._needs_setup:
            AppKit.NSOperationQueue.mainQueue().addOperationWithBlock_(
                lambda: self.firstRun_(None)
            )

    @objc.python_method
    def _install_image(self) -> None:
        """Load PDF and mark it a template **explicitly**.

        The `...Template` filename convention is applied by
        `imageNamed:`, which looks in the bundle's resources. This loads
        by path, so the convention does not fire and the image would
        render as flat black art — invisible in a dark menu bar and
        wrong in the clicked-highlight state. `setTemplate_(True)` is the
        entire light/dark inversion.
        """
        button = self._status_item.button()
        if button is None:
            print("menubar: no status item button; menu bar may be full.", file=sys.stderr)
            return
        template = paths.menubar_template_path()
        image = AppKit.NSImage.alloc().initWithContentsOfFile_(str(template))
        if image is None:
            # Not fatal. A status item with a title and no image is still
            # a working control; one that failed to launch is not.
            print(f"menubar: could not load {template}.", file=sys.stderr)
            return
        image.setSize_(AppKit.NSMakeSize(18.0, 18.0))
        image.setTemplate_(True)
        button.setImage_(image)
        button.setImagePosition_(AppKit.NSImageLeft)
        self._text_region_width = self._measure_text_region(button)

    @objc.python_method
    def _measure_text_region(self, button) -> float:
        """"Reserve a fixed width for the text region so the click
        target does not shift between two Next clicks."

        The reserved width is the widest *persistent* state title. Those
        are the strings the plan requires be shown in full, so they set
        the floor; transient picture labels are then truncated to fit the
        same region (`_fit_to_region`). One constant region for all text
        means the status item's width takes exactly two values — icon
        alone, or icon plus region — and never tracks the string.
        """
        font = button.font() or AppKit.NSFont.menuBarFontOfSize_(0)
        attrs = {AppKit.NSFontAttributeName: font}
        widest = 0.0
        for state in ms.State:
            if not state.title:
                continue
            size = AppKit.NSString.stringWithString_(state.title).sizeWithAttributes_(
                attrs
            )
            widest = max(widest, float(size.width))
        return widest

    @objc.python_method
    def _fit_to_region(self, text: str, button) -> str:
        """Shorten `text` by measurement until it fits the reserved
        region, ellipsising if anything was dropped.

        Measurement rather than a character count, because the menu bar
        font is proportional: 28 narrow characters and 28 wide ones
        differ by more than a factor of two, and a character cap would
        either overflow the region or waste most of it.
        """
        if not text or self._text_region_width <= 0.0:
            return text
        font = button.font() or AppKit.NSFont.menuBarFontOfSize_(0)
        attrs = {AppKit.NSFontAttributeName: font}

        def width(value: str) -> float:
            return float(
                AppKit.NSString.stringWithString_(value)
                .sizeWithAttributes_(attrs)
                .width
            )

        if width(text) <= self._text_region_width:
            return text
        cut = text
        while cut and width(cut + ms.ELLIPSIS) > self._text_region_width:
            cut = cut[:-1]
        return (cut.rstrip() + ms.ELLIPSIS) if cut else ""

    # -- the menu -------------------------------------------------------

    @objc.python_method
    def _build_menu(self) -> None:
        """Menu, built once and re-titled on each poll.

        Rebuilding the whole menu every tick would be simpler to write
        and worse to use: an `NSMenu` that is already open when its items
        are replaced can drop the highlight or close outright, and this
        menu is re-evaluated four times while a user is reading it.
        Titles and enabled-state are mutated in place instead.
        """
        menu = AppKit.NSMenu.alloc().init()
        # Our own setEnabled_ calls are the authority. With
        # autoenablesItems on (the default), AppKit overrules them by
        # walking the responder chain for each action, and every item
        # whose target is set would come back enabled -- including
        # `Adjust the circle…`, which must be disabled while the
        # View is not connected.
        menu.setAutoenablesItems_(False)

        self._items["state"] = self._add(menu, "", None)
        self._items["state"].setEnabled_(False)
        self._items["blank"] = self._add(menu, "Blank the View", "toggleBlank:")
        self._items["pause"] = self._add(
            menu, "Pause on this picture", "togglePause:"
        )
        menu.addItem_(AppKit.NSMenuItem.separatorItem())

        # Key equivalents are the arrow keys with no modifier: they are
        # only live while the menu is open, which is the only time this
        # menu has key focus at all, so no global shortcut is claimed
        # from the user's other apps.
        self._items["next"] = self._add(
            menu, "Next", "next:", key=AppKit.NSRightArrowFunctionKey
        )
        self._items["previous"] = self._add(
            menu, "Previous", "previous:", key=AppKit.NSLeftArrowFunctionKey
        )
        # Step 2 shipped this disabled: the item was listed, but the
        # command schema had no field for it and `control.ALLOWED_KEYS`
        # allow-lists what the display will read, so there was no wire to
        # send it down. Step 4 added `refresh` — a second monotonic
        # counter alongside `advance`, inheriting its replay-safety — and
        # the settings window needs it anyway: changing a source and then
        # waiting up to thirty minutes to find out whether it worked is
        # not a thing that window can ask of anyone.
        self._items["refresh"] = self._add(
            menu, "Check for new pictures now", "refresh:"
        )
        menu.addItem_(AppKit.NSMenuItem.separatorItem())

        # The `Setup needed` title promotes this item. Hidden the
        # rest of the time — a permanent `Finish setup…` on a configured
        # machine is an invitation to redo something already done.
        self._items["setup"] = self._add(menu, fr.MENU_ITEM, "firstRun:")
        self._items["settings"] = self._add(menu, "Settings…", "settings:")
        self._items["calibrate"] = self._add(
            menu, "Adjust the circle…", "calibrate:"
        )
        menu.addItem_(AppKit.NSMenuItem.separatorItem())

        self._items["quit"] = self._add(menu, "Quit", "quit:", key="q")
        self._menu = menu

    @objc.python_method
    def _add(self, menu, title: str, action: str | None, key: str = ""):
        item = AppKit.NSMenuItem.alloc().initWithTitle_action_keyEquivalent_(
            title, action, key
        )
        if action is not None:
            item.setTarget_(self)
        if key and key not in ("q",):
            # Arrow-key equivalents need an explicit empty modifier mask;
            # the default is Command, and ⌘→ is a system text-navigation
            # binding.
            item.setKeyEquivalentModifierMask_(0)
        menu.addItem_(item)
        return item

    # -- polling --------------------------------------------------------

    def pollTick_(self, timer) -> None:
        """The one timer. Broad except for the documented reason: an
        exception off an NSTimer selector kills the run loop, and a menu
        bar that stops updating while still accepting clicks is worse
        than one that is visibly gone."""
        try:
            self._refresh()
        except Exception:
            print(
                f"pollTick_: unexpected exception, ignoring this tick:\n"
                f"{traceback.format_exc()}",
                file=sys.stderr,
            )

    @objc.python_method
    def _refresh(self) -> None:
        now = time.time()
        status = ms.read_status(paths.status_path())
        self._status = status
        self._needs_setup = ms.setup_needed(
            read_json_object(paths.settings_path(), "settings") or {}
        )
        self._state = ms.evaluate_state(
            status, now=now, needs_setup=self._needs_setup
        )
        # The transient label is driven by *observing* last_shown_id
        # change, never by the click that may have caused it.
        self._titles.observe(status.last_shown_id, status.display_label, now)
        self._apply_title(self._titles.active_label(now))
        self._apply_menu()

    @objc.python_method
    def _apply_title(self, transient: str) -> None:
        button = self._status_item.button() if self._status_item else None
        if button is None:
            return
        text = ms.title_for(self._state, transient)
        if text:
            button.setTitle_(" " + self._fit_to_region(text, button))
            # Fixed region. Icon box plus the reserved text width,
            # so the click target is identical for every string.
            self._status_item.setLength_(28.0 + self._text_region_width)
        else:
            button.setTitle_("")
            self._status_item.setLength_(AppKit.NSVariableStatusItemLength)

    @objc.python_method
    def _apply_menu(self) -> None:
        """Re-title and re-enable items for the current state."""
        running = self._state is not ms.State.NOT_SHOWING
        connected = running and self._status.view_connected

        if running:
            # The label of the picture that is actually up, when there is
            # one; otherwise the state string, which is never empty when
            # the state is actionable. `Ready` covers the one remaining
            # case: everything is fine and the source has not named the
            # current picture.
            first = (
                ms.truncate_label(self._status.display_label)
                or self._state.title
                or "Ready"
            )
            self._items["state"].setTitle_(first)
            self._items["state"].setAction_(None)
        else:
            # A dead heartbeat promotes the fix into the first
            # item. A state label with no attached action is a dead end.
            self._items["state"].setTitle_("Start showing pictures")
            self._items["state"].setAction_("startDisplay:")
            self._items["state"].setTarget_(self)
        self._items["state"].setEnabled_(not running)

        self._items["blank"].setTitle_(
            "Show the View again" if self._status.blanked else "Blank the View"
        )
        self._items["pause"].setTitle_(
            "Resume rotation" if self._status.paused else "Pause on this picture"
        )
        for key in ("blank", "pause", "next", "previous"):
            self._items[key].setEnabled_(connected)
        # Refresh is gated on the display *running*, not on the View
        # being connected: re-listing a source is useful — arguably most
        # useful — while the device is unplugged and the user is setting
        # a new source up.
        self._items["refresh"].setEnabled_(running)
        # One settings window at a time. Unlike `Adjust the circle…` it
        # is *not* gated on the View being connected: choosing a source
        # and checking the login boxes are exactly the things someone
        # does before plugging the thing in.
        # Shown when setup is needed, and kept reachable while the
        # flow is open so the item does not vanish mid-setup — disabled
        # rather than hidden, because one flow at a time.
        self._items["setup"].setHidden_(not self._needs_setup)
        self._items["setup"].setEnabled_(self._first_run is None)
        self._items["settings"].setEnabled_(self._settings is None)
        # Disabled while `View not connected` -- live nudging is
        # meaningless without the device. Step 3 built the window, so
        # this is now the only rule governing the item.
        #
        # Also disabled while a session is already open: the window owns
        # a transient preview on the shared control channel, and two of
        # them would fight over it, each clearing the other's nudges on
        # close.
        self._items["calibrate"].setEnabled_(
            connected and self._calibrate is None
        )

    # -- actions --------------------------------------------------------
    #
    # Each one: read the current command file, build the next desired
    # state from it, write it back atomically. Read-modify-write rather
    # than write-from-memory, because the UI is not the only thing that
    # may have touched the file -- a second UI instance, a hand edit, or
    # a leftover from a previous run -- and clobbering a field this click
    # has no opinion about is how `blanked` gets silently cleared by a
    # Pause.

    @objc.python_method
    def _write(self, builder, *args) -> None:
        path = paths.command_path()
        paths.ensure_dir(path.parent)
        current = read_json_object(path, "command") or {}
        data = builder(current, *args)
        # schema carries `written_at`, and nothing on the display
        # side reads it -- which is exactly why it has to be set here
        # rather than left at its dataclass default. It is the only
        # timestamp on the channel, so a stale-looking command file is
        # otherwise indistinguishable from a fresh one when someone is
        # debugging why a click appeared to do nothing.
        data["written_at"] = time.time()
        state = control.parse_control(data)
        if not control.write_control(path, state):
            print(f"menubar: could not write {path}.", file=sys.stderr)

    def toggleBlank_(self, sender) -> None:
        try:
            self._write(ms.command_set_blanked, not self._status.blanked)
        except Exception:
            print(f"toggleBlank_:\n{traceback.format_exc()}", file=sys.stderr)

    def togglePause_(self, sender) -> None:
        try:
            if self._status.paused:
                self._write(ms.command_set_paused, False, None)
            else:
                self._write(
                    ms.command_set_paused, True, self._status.last_shown_id
                )
        except Exception:
            print(f"togglePause_:\n{traceback.format_exc()}", file=sys.stderr)

    def next_(self, sender) -> None:
        try:
            self._write(ms.command_advance, 1)
        except Exception:
            print(f"next_:\n{traceback.format_exc()}", file=sys.stderr)

    def previous_(self, sender) -> None:
        try:
            self._write(ms.command_advance, -1)
        except Exception:
            print(f"previous_:\n{traceback.format_exc()}", file=sys.stderr)

    def refresh_(self, sender) -> None:
        """`Check for new pictures now` — `refresh`
        counter, incremented. Un-blanks for the same reason Next does:
        "any action un-blanks, except Pause", and a refresh whose
        result nobody can see is the class of silent no-op that rule
        exists to eliminate."""
        try:
            self._write(ms.command_refresh)
        except Exception:
            print(f"refresh_:\n{traceback.format_exc()}", file=sys.stderr)

    def settings_(self, sender) -> None:
        """Settings window. One at a time (see `_apply_menu`).

        Imported lazily, exactly as `calibrate_` imports its window and
        for the same reason: this is the largest and newest surface in
        the UI, and a failure to import it must not cost the status item
        that drives the display.
        """
        try:
            if self._settings is not None:
                return
            from ui import settings_window

            controller = settings_window.SettingsController.alloc().init()
            self._settings = controller
            if not controller.start(on_close=self._settings_closed):
                self._settings = None
            self._apply_menu()
        except Exception:
            self._settings = None
            print(f"settings_:\n{traceback.format_exc()}", file=sys.stderr)

    @objc.python_method
    def _settings_closed(self) -> None:
        self._settings = None

    def firstRun_(self, sender) -> None:
        """First-run flow. One at a time, imported lazily for the
        same reason the other two windows are: a failure to import the
        newest surface in the UI must not cost the status item that
        drives the display."""
        try:
            if self._first_run is not None:
                return
            from ui import first_run_window

            controller = first_run_window.FirstRunController.alloc().init()
            self._first_run = controller
            if not controller.start(
                on_close=self._first_run_closed,
                # `Adjust the circle` hands straight over to window
                # rather than telling the user where to find it.
                on_calibrate=lambda: self.calibrate_(None),
            ):
                self._first_run = None
            self._apply_menu()
        except Exception:
            self._first_run = None
            print(f"firstRun_:\n{traceback.format_exc()}", file=sys.stderr)

    @objc.python_method
    def _first_run_closed(self) -> None:
        self._first_run = None

    def calibrate_(self, sender) -> None:
        """Calibration window. One at a time (see `_apply_menu`).

        The controller is imported lazily rather than at module scope so
        that a menu bar can still launch and drive the display if this
        module is broken — the calibration window is the newest and most
        elaborate surface here, and it is not worth the status item.
        """
        try:
            if self._calibrate is not None:
                return
            from ui import calibrate_window

            controller = calibrate_window.CalibrateController.alloc().init()
            self._calibrate = controller
            if not controller.start(on_close=self._calibrate_closed):
                self._calibrate = None
            self._apply_menu()
        except Exception:
            self._calibrate = None
            print(f"calibrate_:\n{traceback.format_exc()}", file=sys.stderr)

    @objc.python_method
    def _calibrate_closed(self) -> None:
        """Called by the window when it tears itself down, so the next
        `Adjust the circle…` opens a fresh session rather than
        re-showing a closed one."""
        self._calibrate = None

    def startDisplay_(self, sender) -> None:
        """Promoted fix: actually bootstrap the display agent.

        Two cases, in order. `kickstart -k` handles a job that is loaded
        but wedged — the common one, and `-k` is right there because the
        point is to replace a process that is not responding. If that
        fails the job is not loaded at all, so `bootstrap` loads it.

        **`bootstrap` is not followed by another `kickstart -k`**, and
        that is a correction rather than an omission: measured here, the
        second `kickstart -k` blocked for the full 10s timeout against a
        job that `bootstrap` had already started milliseconds earlier,
        freezing the menu bar for the whole of it. `bootstrap` starts a
        `RunAtLoad` job by itself; the plain `kickstart` below is the
        no-op-if-running belt to that braces, and without `-k` it has
        nothing to kill and nothing to wait for.

        If both paths fail while the plist exists, the likely
        cause specifically rather than reporting a launchctl exit code —
        Login Items can disable an agent behind the app's back, and
        "check System Settings" is the only sentence that helps.
        """
        try:
            plist = agent_plist_path()
            if not plist.exists():
                self._alert(
                    "No display agent is installed.",
                    "Nothing is set up to show pictures on the View yet.",
                )
                return
            domain = f"gui/{os.getuid()}"
            label = f"{domain}/{DISPLAY_AGENT_LABEL}"
            if self._launchctl(["kickstart", "-k", label]):
                return
            if self._launchctl(["bootstrap", domain, str(plist)]):
                self._launchctl(["kickstart", label])
                return
            self._alert(
                "Couldn't start showing pictures.",
                "Login Items is blocking this — check System Settings → "
                "General → Login Items.",
            )
        except Exception:
            print(f"startDisplay_:\n{traceback.format_exc()}", file=sys.stderr)

    def quit_(self, sender) -> None:
        """Quit stops the whole app, not just these controls.

        The user expects Quit to send the View back to the desktop
        wallpaper, not freeze it on the last picture — a frozen picture
        reads as "stuck", not "off". So Quit boots out the display agent,
        which exits cleanly (its SIGTERM handler terminates the run loop
        with a clean status, so `KeepAlive{SuccessfulExit: false}` does
        not respawn it), destroying its window and revealing the desktop
        underneath. Then the UI quits.

        This does **not** weaken the display's independence from the UI. That guarantee is about the UI *crashing* or being
        force-quit — which reaches none of this code and leaves the
        pictures rotating, exactly as designed. Only the deliberate Quit
        menu action stops the display.

        Reactivation is the existing "Start showing pictures" path
        (`startDisplay_`): relaunch ImageView, the display shows as not
        running, one click brings it back.

        Stopping the display is best-effort and must never prevent the UI
        from quitting — hence the two separate try blocks.
        """
        try:
            domain = f"gui/{os.getuid()}"
            self._launchctl(["bootout", f"{domain}/{DISPLAY_AGENT_LABEL}"])
        except Exception:
            print(f"quit_ (stopping display):\n{traceback.format_exc()}", file=sys.stderr)
        try:
            AppKit.NSApp().terminate_(self)
        except Exception:
            print(f"quit_:\n{traceback.format_exc()}", file=sys.stderr)

    # -- helpers --------------------------------------------------------

    @objc.python_method
    def _launchctl(self, args: list[str]) -> bool:
        """Run one launchctl subcommand. argv list, never `shell=True` — these paths come from `Path.home()` today and from a
        user-chosen folder as soon as Step 4 generates plists.

        Returns success. A timeout counts as failure rather than
        propagating: `launchctl kickstart` on a job whose SIGTERM handler
        is wedged is precisely the situation the user is trying to fix,
        and hanging the UI's main thread on it would take the menu bar
        down too.

        **This does block the main thread for up to `timeout`**, which is
        a real limitation and not a good one — the menu bar stops
        redrawing for the duration. It is bounded and it is on the
        recovery path only (nothing here runs during normal operation),
        so it stays synchronous until installer work gives this
        code a proper home in `ui/service.py`.
        """
        try:
            done = subprocess.run(
                ["/bin/launchctl", *args],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            print(f"launchctl {args}: {exc}", file=sys.stderr)
            return False
        if done.returncode != 0:
            print(
                f"launchctl {args} -> {done.returncode}: "
                f"{done.stderr.strip()}",
                file=sys.stderr,
            )
        return done.returncode == 0

    @objc.python_method
    def _alert(self, message: str, informative: str) -> None:
        alert = AppKit.NSAlert.alloc().init()
        alert.setMessageText_(message)
        alert.setInformativeText_(informative)
        alert.addButtonWithTitle_("OK")
        # An accessory app has no windows, so the alert would otherwise
        # open behind whatever the user is looking at.
        AppKit.NSApp().activateIgnoringOtherApps_(True)
        alert.runModal()


def main() -> int:
    """Run the menu bar. Returns a process exit code.

    The single-instance guard comes first, before any AppKit object is
    built. Two menu bars is not a theoretical concern once Step 5 ships
    the UI LaunchAgent: the agent starts one at login, and the user then
    double-clicks `ImageView.app` — which is the *documented* way to
    launch it — producing a second identical status item with no way to
    tell the two apart, and two processes writing `command.json`.

    Exit **0** on contention, the same as the display's guard and for
    the same reason: `KeepAlive {SuccessfulExit: false}` does not
    respawn a clean exit, so the loser stays down instead of
    respawn-looping against the winner.

    **Exiting silently is a deliberate, and imperfect, choice.** Nothing
    visible happens when the user double-clicks an already-running
    ImageView — no bounce, no window, no error. The status item *is*
    already there, so the honest fix is not an alert (which would be
    noise for what is a no-op) but for the second instance to flash or
    highlight the existing status item before exiting. That needs a
    channel between the two UI processes, which does not exist yet — the
    command/status files are the UI-to-display channel and giving them
    UI-to-UI traffic would blur the separation. Recorded as a known
    rough edge in `ui/README.md` rather than papered over.
    """
    if single_instance.acquire(paths.ui_lock_path(), "menu bar process") is None:
        return 0

    app = AppKit.NSApplication.sharedApplication()
    # No Dock icon, no menu bar menus -- this app *is* a status item.
    # The packaged build sets LSUIElement in Info.plist too: the
    # plist is consulted before main() runs, so setting it only here
    # lets a Dock icon flash at launch.
    app.setActivationPolicy_(AppKit.NSApplicationActivationPolicyAccessory)

    controller = MenuBarController.alloc().init()
    controller.start()
    # Held on the app object: NSStatusItem does not retain its target,
    # and a controller collected out from under the timer takes the menu
    # with it.
    app.setDelegate_(controller)
    print("menubar: running.", file=sys.stderr)
    app.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
