"""The menu bar app. A **separate process** from the
display agent.

Run: `display/.venv/bin/python3 ui/menubar.py`

This file is the AppKit shell and nothing else. Every decision it makes —
which state to show, whether the heartbeat is stale, how to truncate a
label, what the next command file should contain — lives in
`menubar_state.py`, which has no AppKit in it and is where the tests are.
What is left here is the part that can only be verified by looking at a
real menu bar: an `NSStatusItem`, a menu, a timer, and the code that
turns a decision into a `setTitle_` call.

**The two processes never write each other's files**. This one
writes `~/.viewlab/state/command.json` and reads
`~/.viewlab/state/status.json`; the display does exactly the reverse.
There is no other channel between them — no sockets, no notifications,
no shared memory — which is what makes "force-quit the UI and the
pictures keep rotating" true by construction rather than by care.

It also writes a third file, `~/.viewlab/state/ui_status.json`, carrying
one field: `ui_heartbeat_at`, stamped from `pollTick_`. That is **not** a
channel to the display, which never reads it — it is the mirror image of
the display's own `heartbeat_at`, and it exists because `ui.lock` proves
only that this process is *alive*. On 2026-09-08 a wedged menu bar held
that lock while serving nobody, every relaunch found the lock held and
exited 0 exactly as designed, and nothing on the machine could tell that
state from a healthy one. A heartbeat can, because it is written from a
timer: it stops the moment the run loop stops servicing timers, which is
precisely what a wedge is. Nothing in the app reads it yet — acting on
it is a separate, separately-approved change.

**Conventions this file follows, each for a reason already paid for:**

- `@objc.python_method` on every private helper. A plain snake_case
  method on an `NSObject` subclass is exported to the Objective-C
  runtime as a selector, and one of them has already collided with an
  AppKit selector in this project and cost a debugging session.
- A broad `try/except` around the body of **every** selector AppKit
  calls — timer callbacks and menu actions alike. An exception escaping
  an NSTimer selector kills the run loop; an exception escaping a menu
  action lands in AppKit's own dispatch and is at best logged somewhere
  nobody looks. The display agent has carried this rule since Phase 2.
- Reads never raise, writes are atomic write-then-rename (via
  `control.write_control` / `atomic_io`).
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
import traceback
from pathlib import Path

import AppKit
import objc

from display import control, diagnostics, paths, single_instance
from display.config_store import read_json_object
from ui import contention
from ui import first_run_state as fr
from ui import menubar_state as ms
from ui import notice_window
from ui import ui_agent

#: How often the UI re-reads `status.json`. Fast enough that the
#: transient label (a ~3s hold) cannot be missed entirely and that
#: a command's effect appears to land promptly, slow enough that this is
#: a stat call and a small JSON parse a couple of times a second rather
#: than the display's own 4Hz. The display is the real-time end of this
#: relationship; the menu bar is not.
POLL_INTERVAL_S = 0.4

#: Asset, generated by `packaging/make_menubar_template.py`.
#:
#: Resolved through `paths` rather than from `__file__`, because
#: `__file__` inside the bundle points into `Contents/Resources/lib/
#: python3NN.zip` and its `.parent.parent / "packaging"` is a directory
#: that does not exist — the icon would silently fail to load and the
#: status item would come up bare. A *function*, not a constant, so the
#: resolution happens after `sys.frozen` is set rather than at import.

#: The LaunchAgent label this UI drives.
#:
#: Deliberately the *pre-existing source-tree* one (the already
#: installed label stays as it is, only the shipped one changes), because
#: Step 2's job was to drive the display that is actually running on the
#: development machine.
#:
#: RELEASE BLOCKER, open at Step 6. For a packaged install the correct
#: value is `paths.DISPLAY_AGENT_LABEL` (`dev.viewlab.imageview.display`):
#: no other machine has the development agent, so a shipped build points
#: the Restart and Open-at-login controls at a label that does not exist
#: there. This constant was introduced as transitional but never given
#: a removal step. Switching it is a live behaviour change on the
#: development machine, so it is an owner decision, not a sweep.
DISPLAY_AGENT_LABEL = paths.DISPLAY_AGENT_LABEL

#: The two things this menu bar has to say in a window, one slot each.
#:
#: Two slots rather than one because either may be on screen while the
#: other is; and slots at all because a second click on the *same* menu
#: item must re-show the panel already up rather than stack an identical
#: one behind it. That could not happen while these were `runModal()` —
#: a modal blocked the menu — and it is the one thing the conversion
#: gives away. Two clicks on *Start showing pictures* also cost two
#: 5-second main-thread `launchctl` waits; that is unchanged by this
#: phase and `_launchctl` documents it.
#:
#: Namespaced, because `notice_window._SLOTS` is module-level and shared
#: with every other advisory site — a bare "about" is one careless
#: collision away from two unrelated windows evicting each other.
ADVISORY_ABOUT = "menubar.about"
ADVISORY_START_FAILED = "menubar.start_failed"


def agent_plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{DISPLAY_AGENT_LABEL}.plist"


class MenuBarController(AppKit.NSObject):
    """Owns the status item, the menu, and the one poll timer.

    An `NSObject` subclass because AppKit needs a target for the timer
    and for every menu action. Constructed with `alloc().init()`; the
    real setup is in `start`, so that a failure to build the status item
    is a logged error rather than an exception thrown out of `init`.
    """

    def init(self):
        self = objc.super(MenuBarController, self).init()
        if self is None:
            return None
        self._status_item = None
        self._menu = None
        self._items = {}
        self._timer = None
        self._titles = ms.TitleTracker()
        self._state = ms.State.NOT_SHOWING
        self._status = ms.Status()
        self._needs_setup = False
        self._text_region_width = 0.0
        # Last `ui_heartbeat_at` this process wrote, throttling the
        # heartbeat down from the 0.4s poll to ms.UI_HEARTBEAT_INTERVAL_S.
        # Same shape as `app.py`'s `_last_heartbeat_at`, including the
        # 0.0 seed: it makes the first tick after startup write
        # unconditionally.
        self._last_ui_heartbeat_at = 0.0
        # Whether the last heartbeat write failed, so that only the
        # transitions are logged. See `_write_ui_heartbeat`.
        self._ui_heartbeat_failing = False
        # This process's executable path as the kernel records it, read
        # once rather than on every heartbeat: it cannot change for the
        # life of the process, and `proc_pidpath` is a syscall that would
        # otherwise run every 2 seconds forever. It is published in
        # `ui_status.json` so that a later arriving instance can say what
        # the holder *is*, not only that it exists.
        self._own_exe = contention.own_exe()
        # The open calibration window, or None. Held here rather
        # than on the app object because the menu's enabled-state depends
        # on it, and because nothing else retains it — a
        # CalibrateController collected out from under its own key
        # monitor takes both its windows with it.
        self._calibrate = None
        # The open settings window, or None. Held for the same
        # reason `_calibrate` is: nothing else retains it, and the menu's
        # enabled-state depends on whether one is already open.
        self._settings = None
        # The open first-run flow, or None. Same reasoning as the
        # two above.
        self._first_run = None
        return self

    # -- setup ----------------------------------------------------------

    @objc.python_method
    def start(self) -> None:
        bar = AppKit.NSStatusBar.systemStatusBar()
        self._status_item = bar.statusItemWithLength_(
            AppKit.NSVariableStatusItemLength
        )
        self._install_image()
        self._build_menu()
        self._status_item.setMenu_(self._menu)
        # Refresh once synchronously so the first thing drawn is already
        # correct -- otherwise the status item appears with a stale
        # "Not showing pictures" for up to POLL_INTERVAL_S even when the
        # display is running fine, which is exactly the misleading state
        # the precedence list is ordered to avoid.
        self._refresh()
        # ** DO NOT MOVE THIS TIMER TO NSRunLoopCommonModes. **
        # `scheduledTimerWithTimeInterval_...` adds it to
        # NSDefaultRunLoopMode only, and that is load-bearing now that the
        # tick carries `ui_heartbeat_at`. `runModal()` spins the run loop
        # in NSModalPanelRunLoopMode, where default-mode timers stop
        # firing — which is precisely why a heartbeat on this timer can
        # detect a modal wedge, the leading suspect for 2026-09-08. Common
        # modes would keep it ticking straight through one and report a
        # process that cannot answer anything as healthy: worse than no
        # heartbeat, because it would be believed.
        #
        # What is measured and what is not: the mode contract itself is
        # measured, here, by `RunLoopModeContractTests` in
        # `ui/test_menubar.py`, with a live positive control. The
        # end-to-end path is NOT — no session has watched a real
        # `NSAlert.runModal()` in this process and observed the heartbeat
        # go stale, because staging one puts a modal panel on the owner's
        # live screen. The wedge that has actually been reproduced is a
        # `kill -STOP`, which stops the whole process and is a strictly
        # stronger stop than a modal run loop. So: *a* wedge is detected,
        # measured; *the* suspected wedge is derived from the mode
        # contract plus Apple's documentation, not observed.
        self._timer = AppKit.NSTimer.scheduledTimerWithTimeInterval_target_selector_userInfo_repeats_(
            POLL_INTERVAL_S, self, "pollTick:", None, True
        )
        # The flow opens by itself on a config that has never been
        # set up. `_refresh` has just computed `_needs_setup` from the
        # same `setup_needed` the menu title uses, so the window and the
        # `Setup needed` title can never disagree.
        #
        # Deferred to the next run-loop pass rather than called here: the
        # status item is not yet installed in the menu bar at this point,
        # and opening a window that calls `activateIgnoringOtherApps_`
        # before it is would leave an accessory app with a key window and
        # no visible status item behind it.
        if self._needs_setup:
            AppKit.NSOperationQueue.mainQueue().addOperationWithBlock_(
                lambda: self.firstRun_(None)
            )

    @objc.python_method
    def _install_image(self) -> None:
        """Load PDF and mark it a template **explicitly**.

        The `...Template` filename convention is applied by
        `imageNamed:`, which looks in the bundle's resources. This loads
        by path, so the convention does not fire and the image would
        render as flat black art — invisible in a dark menu bar and
        wrong in the clicked-highlight state. `setTemplate_(True)` is the
        entire light/dark inversion.
        """
        button = self._status_item.button()
        if button is None:
            print("menubar: no status item button; menu bar may be full.", file=sys.stderr)
            return
        template = paths.menubar_template_path()
        image = AppKit.NSImage.alloc().initWithContentsOfFile_(str(template))
        if image is None:
            # Not fatal. A status item with a title and no image is still
            # a working control; one that failed to launch is not.
            print(f"menubar: could not load {template}.", file=sys.stderr)
            return
        image.setSize_(AppKit.NSMakeSize(18.0, 18.0))
        image.setTemplate_(True)
        button.setImage_(image)
        button.setImagePosition_(AppKit.NSImageLeft)
        self._text_region_width = self._measure_text_region(button)

    @objc.python_method
    def _measure_text_region(self, button) -> float:
        """"Reserve a fixed width for the text region so the click
        target does not shift between two Next clicks."

        The reserved width is the widest *persistent* state title. Those
        are the strings the plan requires be shown in full, so they set
        the floor; transient picture labels are then truncated to fit the
        same region (`_fit_to_region`). One constant region for all text
        means the status item's width takes exactly two values — icon
        alone, or icon plus region — and never tracks the string.
        """
        font = button.font() or AppKit.NSFont.menuBarFontOfSize_(0)
        attrs = {AppKit.NSFontAttributeName: font}
        widest = 0.0
        for state in ms.State:
            if not state.title:
                continue
            size = AppKit.NSString.stringWithString_(state.title).sizeWithAttributes_(
                attrs
            )
            widest = max(widest, float(size.width))
        return widest

    @objc.python_method
    def _fit_to_region(self, text: str, button) -> str:
        """Shorten `text` by measurement until it fits the reserved
        region, ellipsising if anything was dropped.

        Measurement rather than a character count, because the menu bar
        font is proportional: 28 narrow characters and 28 wide ones
        differ by more than a factor of two, and a character cap would
        either overflow the region or waste most of it.
        """
        if not text or self._text_region_width <= 0.0:
            return text
        font = button.font() or AppKit.NSFont.menuBarFontOfSize_(0)
        attrs = {AppKit.NSFontAttributeName: font}

        def width(value: str) -> float:
            return float(
                AppKit.NSString.stringWithString_(value)
                .sizeWithAttributes_(attrs)
                .width
            )

        if width(text) <= self._text_region_width:
            return text
        cut = text
        while cut and width(cut + ms.ELLIPSIS) > self._text_region_width:
            cut = cut[:-1]
        return (cut.rstrip() + ms.ELLIPSIS) if cut else ""

    # -- the menu -------------------------------------------------------

    @objc.python_method
    def _build_menu(self) -> None:
        """Menu, built once and re-titled on each poll.

        Rebuilding the whole menu every tick would be simpler to write
        and worse to use: an `NSMenu` that is already open when its items
        are replaced can drop the highlight or close outright. Titles and
        enabled-state are mutated in place instead.

        This docstring used to add "and this menu is re-evaluated four
        times while a user is reading it". **Measured: zero.** An open
        menu tracks in `NSEventTrackingRunLoopMode`, where a
        default-mode timer does not fire at all, so `pollTick_` stops for
        as long as the menu is on screen and the menu a user is reading
        is frozen at whatever it said when it opened. That was a harmless
        inaccuracy until this tick started carrying `ui_heartbeat_at`;
        now the same pause reads as staleness, so it is written down
        rather than repeated. See `_write_ui_heartbeat`.
        """
        menu = AppKit.NSMenu.alloc().init()
        # Our own setEnabled_ calls are the authority. With
        # autoenablesItems on (the default), AppKit overrules them by
        # walking the responder chain for each action, and every item
        # whose target is set would come back enabled -- including
        # `Adjust the circle…`, which must be disabled while the
        # View is not connected.
        menu.setAutoenablesItems_(False)

        self._items["state"] = self._add(menu, "", None)
        self._items["state"].setEnabled_(False)
        self._items["blank"] = self._add(menu, "Blank the View", "toggleBlank:")
        self._items["pause"] = self._add(
            menu, "Pause on this picture", "togglePause:"
        )
        menu.addItem_(AppKit.NSMenuItem.separatorItem())

        # Key equivalents are the arrow keys with no modifier: they are
        # only live while the menu is open, which is the only time this
        # menu has key focus at all, so no global shortcut is claimed
        # from the user's other apps.
        self._items["next"] = self._add(
            menu, "Next", "next:", key=AppKit.NSRightArrowFunctionKey
        )
        self._items["previous"] = self._add(
            menu, "Previous", "previous:", key=AppKit.NSLeftArrowFunctionKey
        )
        # Step 2 shipped this disabled: the item was listed, but the
        # command schema had no field for it and `control.ALLOWED_KEYS`
        # allow-lists what the display will read, so there was no wire to
        # send it down. Step 4 added `refresh` — a second monotonic
        # counter alongside `advance`, inheriting its replay-safety — and
        # the settings window needs it anyway: changing a source and then
        # waiting up to thirty minutes to find out whether it worked is
        # not a thing that window can ask of anyone.
        self._items["refresh"] = self._add(
            menu, "Check for new pictures now", "refresh:"
        )
        menu.addItem_(AppKit.NSMenuItem.separatorItem())

        # The `Setup needed` title promotes this item. Hidden the
        # rest of the time — a permanent `Finish setup…` on a configured
        # machine is an invitation to redo something already done.
        self._items["setup"] = self._add(menu, fr.MENU_ITEM, "firstRun:")
        self._items["settings"] = self._add(menu, "Settings…", "settings:")
        self._items["calibrate"] = self._add(
            menu, "Adjust the circle…", "calibrate:"
        )
        menu.addItem_(AppKit.NSMenuItem.separatorItem())

        self._items["about"] = self._add(menu, "About ImageView", "about:")
        self._items["quit"] = self._add(menu, "Quit", "quit:", key="q")
        self._menu = menu

    @objc.python_method
    def _add(self, menu, title: str, action: str | None, key: str = ""):
        item = AppKit.NSMenuItem.alloc().initWithTitle_action_keyEquivalent_(
            title, action, key
        )
        if action is not None:
            item.setTarget_(self)
        if key and key not in ("q",):
            # Arrow-key equivalents need an explicit empty modifier mask;
            # the default is Command, and ⌘→ is a system text-navigation
            # binding.
            item.setKeyEquivalentModifierMask_(0)
        menu.addItem_(item)
        return item

    # -- polling --------------------------------------------------------

    def pollTick_(self, timer) -> None:
        """The one timer. Broad except for the documented reason: an
        exception off an NSTimer selector kills the run loop, and a menu
        bar that stops updating while still accepting clicks is worse
        than one that is visibly gone.

        The heartbeat goes **first**, and this is a deliberate divergence
        from `app.py`, which writes its heartbeat last inside the same
        shared `try`. The two have different stakes. A display heartbeat
        suppressed by an unrelated exception costs a menu title that
        reads `Not showing pictures` and offers an idempotent
        `Start showing pictures`. A *UI* heartbeat suppressed the same way
        would eventually be read as "this process is wedged, kill it" —
        so a bug in `_refresh` would present as a wedge, and the remedy
        for a wedge is a SIGKILL of a process whose run loop was fine.

        Ordering it first makes the heartbeat mean exactly one thing:
        **an NSTimer fired**, i.e. this run loop is still servicing
        timers. That is the property that the incident destroyed and the
        only property `ui.lock` cannot express.

        **Two `try` blocks, not one**, and that is the other half of the
        same argument. Ordering alone would leave the mirror-image
        coupling: anything escaping `_write_ui_heartbeat` would suppress
        `_refresh` on every tick, permanently, while printing a traceback
        at 0.4s — 216,000 a day through a rotated 10 MB log, which is the
        anti-diagnostic `_write_ui_heartbeat` takes care to avoid one
        level down. Independent blocks buy both properties at once, and
        they stop "this method cannot raise" from being a safety-critical
        claim a future editor has to keep true. (It is *nearly* true and
        not quite: `paths.ui_status_path()` goes through `Path.home()`,
        which raises `RuntimeError` when a home directory cannot be
        resolved — not in the tuple `write_ui_heartbeat` catches.)
        """
        try:
            self._write_ui_heartbeat()
        except Exception:
            print(
                f"pollTick_: the heartbeat raised, ignoring it this tick "
                f"— the menu below is unaffected:\n{traceback.format_exc()}",
                file=sys.stderr,
            )
        try:
            self._refresh()
        except Exception:
            print(
                f"pollTick_: unexpected exception, ignoring this tick:\n"
                f"{traceback.format_exc()}",
                file=sys.stderr,
            )

    @objc.python_method
    def _write_ui_heartbeat(self) -> None:
        """`ui_heartbeat_at` — how anything tells a *serving* menu bar
        from one that is merely alive and holding `ui.lock`.

        Throttled to `ms.UI_HEARTBEAT_INTERVAL_S` rather than written on
        every 0.4s tick; see that constant for the arithmetic.

        Only the timer ever calls this. Not `start()`, not `main()`,
        deliberately: a heartbeat written from anywhere but a timer
        callback would assert liveness this process has not yet
        demonstrated. A UI that has built its status item but never
        reached `app.run()` — one of the two mechanisms that fit the
        2026-09-08 incident — correctly has no heartbeat at all, and
        `is_stale()` already answers `True` for an absent one.

        Nothing removes the file on quit. A stale heartbeat left behind by
        a process that exited is a true statement: that process is not
        serving. Deleting it would be a second writer's worth of race for
        no gain.
        """
        now = time.time()
        elapsed = now - self._last_ui_heartbeat_at
        # `0 <= elapsed` is not redundant. Without it, an NTP step
        # backwards by T makes `elapsed` negative, the throttle
        # short-circuits, and nothing is written for T + 2s — while
        # `is_stale()` deliberately treats a future timestamp as fresh, so
        # a reader sees a healthy process for that entire window and a
        # wedge inside it is invisible. `app.py:_write_heartbeat` has the
        # same shape without this guard; there it costs a wrong menu
        # title, here it costs the only signal this file exists to carry.
        # Fixing it there is owed and is not this change's to make.
        if 0 <= elapsed < ms.UI_HEARTBEAT_INTERVAL_S:
            return
        # Advanced whether or not the write succeeded. A disk that cannot
        # take this write will not take the next one either, and retrying
        # at 4Hz against a full disk would turn a reporting failure into
        # a performance one. `write_ui_heartbeat` never raises; it returns
        # False, and the resulting staleness is itself the report.
        self._last_ui_heartbeat_at = now
        # The four process fields ride the same atomic write as the
        # stamp, so a reader can never catch a fresh timestamp against a
        # previous process's pid. `armed_stacks_path()` is read on every
        # write rather than captured once because arming happens in
        # `main()`, after this object exists, and a value cached at
        # `init` would be permanently None.
        stacks = diagnostics.armed_stacks_path()
        failing = not ms.write_ui_heartbeat(
            paths.ui_status_path(),
            now,
            pid=os.getpid(),
            exe=self._own_exe,
            stacks_armed=stacks is not None,
            stacks_path=str(stacks) if stacks is not None else None,
        )
        if failing != self._ui_heartbeat_failing:
            # Log the *transitions* only, never the state. A menu bar that
            # cannot write this file goes stale and therefore reads as
            # wedged while its run loop is perfectly healthy, and the only
            # thing that distinguishes the two is a line saying so. At one
            # line every 2s it would instead be 43,000 lines a day pushing
            # everything else out of a rotated 10 MB log, which is how a
            # diagnostic becomes an anti-diagnostic.
            #
            # ** THIS IS NOT THE ONLY FALSE POSITIVE, AND AN EARLIER
            # VERSION OF THIS COMMENT CLAIMED IT WAS. ** Measured, 0.1s
            # timer, 1.0s per mode: NSDefaultRunLoopMode 11 fires,
            # NSModalPanelRunLoopMode 0, NSEventTrackingRunLoopMode 0. The
            # very property that lets this detect a modal wedge — a
            # default-mode timer stops in every other mode — also freezes
            # the heartbeat during three ordinary, intentional
            # interactions:
            #
            #   * an open menu (event tracking), for as long as it is read;
            #   * the three alerts in Settings, and the three in Adjust
            #     the circle, which are `runModal()`.
            #
            # 🔵 **The list has shrunk twice and this comment has been
            # wrong after each shrink.** It once named the file picker in
            # Settings and First Run; Phase 3 made both sheets, and a
            # sheet spins no nested run loop. It then named "the About
            # box and `_alert()`" — Phase 5 converted every modal in this
            # file, both of First Run's, and the one in Adjust the circle
            # that fires before its windows exist. None of those freezes
            # this stamp any more.
            #
            # So a stale `ui_heartbeat_at` means "not servicing default-
            # mode timers", which is still a superset of "wedged".
            # Nothing may act destructively on staleness alone: a Phase 4
            # that offered to SIGKILL on this signal would kill a healthy
            # app because somebody left a Settings alert on screen.
            #
            # ⚠️ **The measurement behind that conclusion has outlived
            # its recipe, which is worth knowing before anyone tries to
            # reproduce it.** M1 measured the About box freezing this
            # stamp for **51.2 seconds** on macOS 26.6.2, 2026-09-10 —
            # ten times the 5s threshold. It was true of a modal run
            # loop, and modal run loops still exist; but the About box is
            # no longer one, so re-running M1 through About now finds no
            # freeze at all. Use a Settings alert instead. The conclusion
            # is unchanged; only the way to see it again has moved.
            # A default-mode timer cannot tell modally
            # wedged from modally busy on purpose; the corroborating
            # common-modes signal that can is recorded against Phase 3/4
            # in docs/plans/ui-wedge-remediation.md.
            self._ui_heartbeat_failing = failing
            diagnostics.note(
                f"menubar: could not write {paths.ui_status_path()}; this "
                f"process is healthy but will read as wedged until it can."
                if failing
                else f"menubar: {paths.ui_status_path()} is writable again."
            )

    @objc.python_method
    def _refresh(self) -> None:
        now = time.time()
        status = ms.read_status(paths.status_path())
        self._status = status
        self._needs_setup = ms.setup_needed(
            read_json_object(paths.settings_path(), "settings") or {}
        )
        self._state = ms.evaluate_state(
            status, now=now, needs_setup=self._needs_setup
        )
        # The transient label is driven by *observing* last_shown_id
        # change, never by the click that may have caused it.
        self._titles.observe(status.last_shown_id, status.display_label, now)
        self._apply_title(self._titles.active_label(now))
        self._apply_menu()

    @objc.python_method
    def _apply_title(self, transient: str) -> None:
        button = self._status_item.button() if self._status_item else None
        if button is None:
            return
        text = ms.title_for(self._state, transient)
        if text:
            button.setTitle_(" " + self._fit_to_region(text, button))
            # Fixed region. Icon box plus the reserved text width,
            # so the click target is identical for every string.
            self._status_item.setLength_(28.0 + self._text_region_width)
        else:
            button.setTitle_("")
            self._status_item.setLength_(AppKit.NSVariableStatusItemLength)

    @objc.python_method
    def _apply_menu(self) -> None:
        """Re-title and re-enable items for the current state."""
        running = self._state is not ms.State.NOT_SHOWING
        connected = running and self._status.view_connected

        if running:
            # The label of the picture that is actually up, when there is
            # one; otherwise the state string, which is never empty when
            # the state is actionable. `Ready` covers the one remaining
            # case: everything is fine and the source has not named the
            # current picture.
            first = (
                ms.truncate_label(self._status.display_label)
                or self._state.title
                or "Ready"
            )
            self._items["state"].setTitle_(first)
            self._items["state"].setAction_(None)
        else:
            # A dead heartbeat promotes the fix into the first
            # item. A state label with no attached action is a dead end.
            self._items["state"].setTitle_("Start showing pictures")
            self._items["state"].setAction_("startDisplay:")
            self._items["state"].setTarget_(self)
        self._items["state"].setEnabled_(not running)

        self._items["blank"].setTitle_(
            "Show the View again" if self._status.blanked else "Blank the View"
        )
        self._items["pause"].setTitle_(
            "Resume rotation" if self._status.paused else "Pause on this picture"
        )
        for key in ("blank", "pause", "next", "previous"):
            self._items[key].setEnabled_(connected)
        # Refresh is gated on the display *running*, not on the View
        # being connected: re-listing a source is useful — arguably most
        # useful — while the device is unplugged and the user is setting
        # a new source up.
        self._items["refresh"].setEnabled_(running)
        # One settings window at a time. Unlike `Adjust the circle…` it
        # is *not* gated on the View being connected: choosing a source
        # and checking the login boxes are exactly the things someone
        # does before plugging the thing in.
        # Shown when setup is needed, and kept reachable while the
        # flow is open so the item does not vanish mid-setup — disabled
        # rather than hidden, because one flow at a time.
        self._items["setup"].setHidden_(not self._needs_setup)
        self._items["setup"].setEnabled_(self._first_run is None)
        self._items["settings"].setEnabled_(self._settings is None)
        # Disabled while `View not connected` -- live nudging is
        # meaningless without the device. Step 3 built the window, so
        # this is now the only rule governing the item.
        #
        # Also disabled while a session is already open: the window owns
        # a transient preview on the shared control channel, and two of
        # them would fight over it, each clearing the other's nudges on
        # close.
        self._items["calibrate"].setEnabled_(
            connected and self._calibrate is None
        )

    # -- actions --------------------------------------------------------
    #
    # Each one: read the current command file, build the next desired
    # state from it, write it back atomically. Read-modify-write rather
    # than write-from-memory, because the UI is not the only thing that
    # may have touched the file -- a second UI instance, a hand edit, or
    # a leftover from a previous run -- and clobbering a field this click
    # has no opinion about is how `blanked` gets silently cleared by a
    # Pause.

    @objc.python_method
    def _write(self, builder, *args) -> None:
        path = paths.command_path()
        paths.ensure_dir(path.parent)
        current = read_json_object(path, "command") or {}
        data = builder(current, *args)
        # schema carries `written_at`, and nothing on the display
        # side reads it -- which is exactly why it has to be set here
        # rather than left at its dataclass default. It is the only
        # timestamp on the channel, so a stale-looking command file is
        # otherwise indistinguishable from a fresh one when someone is
        # debugging why a click appeared to do nothing.
        data["written_at"] = time.time()
        state = control.parse_control(data)
        if not control.write_control(path, state):
            print(f"menubar: could not write {path}.", file=sys.stderr)

    def toggleBlank_(self, sender) -> None:
        try:
            self._write(ms.command_set_blanked, not self._status.blanked)
        except Exception:
            print(f"toggleBlank_:\n{traceback.format_exc()}", file=sys.stderr)

    def togglePause_(self, sender) -> None:
        try:
            if self._status.paused:
                self._write(ms.command_set_paused, False, None)
            else:
                self._write(
                    ms.command_set_paused, True, self._status.last_shown_id
                )
        except Exception:
            print(f"togglePause_:\n{traceback.format_exc()}", file=sys.stderr)

    def next_(self, sender) -> None:
        try:
            self._write(ms.command_advance, 1)
        except Exception:
            print(f"next_:\n{traceback.format_exc()}", file=sys.stderr)

    def previous_(self, sender) -> None:
        try:
            self._write(ms.command_advance, -1)
        except Exception:
            print(f"previous_:\n{traceback.format_exc()}", file=sys.stderr)

    def refresh_(self, sender) -> None:
        """`Check for new pictures now` — `refresh`
        counter, incremented. Un-blanks for the same reason Next does:
        "any action un-blanks, except Pause", and a refresh whose
        result nobody can see is the class of silent no-op that rule
        exists to eliminate."""
        try:
            self._write(ms.command_refresh)
        except Exception:
            print(f"refresh_:\n{traceback.format_exc()}", file=sys.stderr)

    def settings_(self, sender) -> None:
        """Settings window. One at a time (see `_apply_menu`).

        Imported lazily, exactly as `calibrate_` imports its window and
        for the same reason: this is the largest and newest surface in
        the UI, and a failure to import it must not cost the status item
        that drives the display.
        """
        try:
            if self._settings is not None:
                return
            from ui import settings_window

            controller = settings_window.SettingsController.alloc().init()
            self._settings = controller
            if not controller.start(on_close=self._settings_closed):
                self._settings = None
            self._apply_menu()
        except Exception:
            self._settings = None
            print(f"settings_:\n{traceback.format_exc()}", file=sys.stderr)

    @objc.python_method
    def _settings_closed(self) -> None:
        self._settings = None

    def firstRun_(self, sender) -> None:
        """First-run flow. One at a time, imported lazily for the
        same reason the other two windows are: a failure to import the
        newest surface in the UI must not cost the status item that
        drives the display."""
        try:
            if self._first_run is not None:
                return
            from ui import first_run_window

            controller = first_run_window.FirstRunController.alloc().init()
            self._first_run = controller
            if not controller.start(
                on_close=self._first_run_closed,
                # `Adjust the circle` hands straight over to window
                # rather than telling the user where to find it.
                on_calibrate=lambda: self.calibrate_(None),
            ):
                self._first_run = None
            self._apply_menu()
        except Exception:
            self._first_run = None
            print(f"firstRun_:\n{traceback.format_exc()}", file=sys.stderr)

    @objc.python_method
    def _first_run_closed(self) -> None:
        self._first_run = None
        # Finishing setup should make pictures appear, not leave the user
        # at "Not showing pictures" wondering what setup accomplished.
        # first-run has just persisted the source and calibration; this
        # installs (if needed) and starts the display agent that draws
        # them. startDisplay_ is self-installing and idempotent, so this
        # is safe whether or not an agent already exists.
        self.startDisplay_(None)

    def calibrate_(self, sender) -> None:
        """Calibration window. One at a time (see `_apply_menu`).

        The controller is imported lazily rather than at module scope so
        that a menu bar can still launch and drive the display if this
        module is broken — the calibration window is the newest and most
        elaborate surface here, and it is not worth the status item.
        """
        try:
            if self._calibrate is not None:
                return
            from ui import calibrate_window

            controller = calibrate_window.CalibrateController.alloc().init()
            self._calibrate = controller
            if not controller.start(on_close=self._calibrate_closed):
                self._calibrate = None
            self._apply_menu()
        except Exception:
            self._calibrate = None
            print(f"calibrate_:\n{traceback.format_exc()}", file=sys.stderr)

    @objc.python_method
    def _calibrate_closed(self) -> None:
        """Called by the window when it tears itself down, so the next
        `Adjust the circle…` opens a fresh session rather than
        re-showing a closed one."""
        self._calibrate = None

    def startDisplay_(self, sender) -> None:
        """Promoted fix: actually bootstrap the display agent.

        Two cases, in order. `kickstart -k` handles a job that is loaded
        but wedged — the common one, and `-k` is right there because the
        point is to replace a process that is not responding. If that
        fails the job is not loaded at all, so `bootstrap` loads it.

        **`bootstrap` is not followed by another `kickstart -k`**, and
        that is a correction rather than an omission: measured here, the
        second `kickstart -k` blocked for the full 10s timeout against a
        job that `bootstrap` had already started milliseconds earlier,
        freezing the menu bar for the whole of it. `bootstrap` starts a
        `RunAtLoad` job by itself; the plain `kickstart` below is the
        no-op-if-running belt to that braces, and without `-k` it has
        nothing to kill and nothing to wait for.

        If both paths fail while the plist exists, the likely
        cause specifically rather than reporting a launchctl exit code —
        Login Items can disable an agent behind the app's back, and
        "check System Settings" is the only sentence that helps.
        """
        try:
            plist = agent_plist_path()
            domain = f"gui/{os.getuid()}"
            label = f"{domain}/{DISPLAY_AGENT_LABEL}"
            # Self-installing. If the display agent has never been set up
            # — which on a fresh install is *always*, since nothing else
            # creates it — generate its plist pointing at this bundle
            # (`ImageView --display`) and bootstrap it. install_display
            # boots out, writes, and bootstraps, so it also cleanly
            # restarts an already-installed-but-stopped agent, which is
            # the other case this action exists for. v1.0.0 shipped
            # without this and dead-ended here with "No display agent
            # installed" on every machine but the one it was built on.
            if not plist.exists():
                if ui_agent.install_display():
                    return
                self._advise(
                    ADVISORY_START_FAILED,
                    "Couldn't start showing pictures.",
                    "The part of ImageView that draws the pictures could not "
                    "be installed. If ImageView is not in your Applications "
                    "folder, move it there, open it again, and choose Start "
                    "showing pictures.",
                )
                return
            if self._launchctl(["kickstart", "-k", label]):
                return
            if self._launchctl(["bootstrap", domain, str(plist)]):
                self._launchctl(["kickstart", label])
                return
            self._advise(
                ADVISORY_START_FAILED,
                "Couldn't start showing pictures.",
                "Login Items is blocking this. Check System Settings → "
                "General → Login Items, then choose Start showing pictures "
                "again.",
            )
        except Exception:
            print(f"startDisplay_:\n{traceback.format_exc()}", file=sys.stderr)

    def quit_(self, sender) -> None:
        """Quit stops the whole app, not just these controls.

        The user expects Quit to send the View back to the desktop
        wallpaper, not freeze it on the last picture — a frozen picture
        reads as "stuck", not "off". So Quit boots out the display agent,
        which exits cleanly (its SIGTERM handler terminates the run loop
        with a clean status, so `KeepAlive{SuccessfulExit: false}` does
        not respawn it), destroying its window and revealing the desktop
        underneath. Then the UI quits.

        This does **not** weaken the display's independence from the UI. That guarantee is about the UI *crashing* or being
        force-quit — which reaches none of this code and leaves the
        pictures rotating, exactly as designed. Only the deliberate Quit
        menu action stops the display.

        Reactivation is the existing "Start showing pictures" path
        (`startDisplay_`): relaunch ImageView, the display shows as not
        running, one click brings it back.

        Stopping the display is best-effort and must never prevent the UI
        from quitting — hence the two separate try blocks.
        """
        try:
            domain = f"gui/{os.getuid()}"
            self._launchctl(["bootout", f"{domain}/{DISPLAY_AGENT_LABEL}"])
        except Exception:
            print(f"quit_ (stopping display):\n{traceback.format_exc()}", file=sys.stderr)
        try:
            AppKit.NSApp().terminate_(self)
        except Exception:
            print(f"quit_:\n{traceback.format_exc()}", file=sys.stderr)

    # -- helpers --------------------------------------------------------

    @objc.python_method
    def _launchctl(self, args: list[str]) -> bool:
        """Run one launchctl subcommand. argv list, never `shell=True` — these paths come from `Path.home()` today and from a
        user-chosen folder as soon as Step 4 generates plists.

        Returns success. A timeout counts as failure rather than
        propagating: `launchctl kickstart` on a job whose SIGTERM handler
        is wedged is precisely the situation the user is trying to fix,
        and hanging the UI's main thread on it would take the menu bar
        down too.

        **This does block the main thread for up to `timeout`**, which is
        a real limitation and not a good one — the menu bar stops
        redrawing for the duration. It is bounded and it is on the
        recovery path only (nothing here runs during normal operation),
        so it stays synchronous until installer work gives this
        code a proper home in `ui/service.py`.
        """
        try:
            done = subprocess.run(
                ["/bin/launchctl", *args],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
            )
        except (OSError, subprocess.SubprocessError) as exc:
            print(f"launchctl {args}: {exc}", file=sys.stderr)
            return False
        if done.returncode != 0:
            print(
                f"launchctl {args} -> {done.returncode}: "
                f"{done.stderr.strip()}",
                file=sys.stderr,
            )
        return done.returncode == 0

    def about_(self, sender) -> None:
        """Show the About box.

        The version is read from the **running bundle's** Info.plist, not
        from a constant in the source. A hardcoded string here would be a
        fourth place the version lives, and it would be the one users
        read — the release gate asserts that setup.py and the git tag
        agree precisely so this cannot drift, and re-introducing the drift
        in the About box would be self-defeating.

        `NSBundle.mainBundle()` is the installed .app when packaged; run
        from source it returns the interpreter's bundle and the key is
        absent, which `about_text` degrades to "unknown version" rather
        than raising. An About box is never worth a crash.
        """
        version = AppKit.NSBundle.mainBundle().objectForInfoDictionaryKey_(
            "CFBundleShortVersionString"
        )
        title, body = ms.about_text(version)
        self._advise(ADVISORY_ABOUT, title, body)

    @objc.python_method
    def _advise(self, slot: str, message: str, informative: str) -> None:
        """Say one thing to the user, in a **non-modal panel**.

        🔴 **This was `_alert`, and it was `NSAlert.runModal()` plus
        `activateIgnoringOtherApps_(True)` until Phase 5.** Both calls
        were wrong here, for reasons this app has measured rather than
        assumed:

        * `runModal()` spins the run loop in `NSModalPanelRunLoopMode`,
          where the default-mode timer that stamps `ui_heartbeat_at`
          fires **zero** times. MEASURED on macOS 26.6.2, 2026-09-10:
          opening this app's About box froze that stamp **byte-identical
          across ten seconds, 51.2 seconds end to end**. A modal run loop
          also never *fetches* a Quit Apple Event, which is the whole of
          "Quit did nothing, Force Quit worked".
        * `activateIgnoringOtherApps_` is reported to fail intermittently
          on macOS 26 (DevForums 807805 / FB21087054). When it does, the
          modal this app has no window to fall back on opens **behind
          everything** — invisible, unanswerable, and holding the run
          loop forever. That is the shape of 2026-09-08.

        This method is renamed rather than rewritten in place so that
        `_alert` means what it says everywhere in this package: a real
        modal alert, of which this file now has none.

        **It returns immediately.** Every caller here is a site where the
        alert was the last statement before a `return` and nothing read a
        result, so the flow is unchanged; a new caller must check its
        own.

        🔵 **The anti-stacking rule used to live here, on an ivar, and
        moved down to `notice_window._SLOTS`.** A modal blocked a second
        click and a panel does not, so this file grew a "same words,
        re-show; different words, replace" rule — and then
        `calibrate_window` needed the identical rule and **structurally
        could not hold an ivar**: it shows its advisory, returns False,
        and its caller drops it. Two implementations of one question is
        how this app once told a user its picture source was empty while
        fifty pictures rotated on the glass. There is one, and both sites
        name a slot.
        """
        notice_window.advise(message, informative, slot=slot)


def main() -> int:
    """Run the menu bar. Returns a process exit code.

    The single-instance guard comes first, before any AppKit object is
    built. Two menu bars is not a theoretical concern once Step 5 ships
    the UI LaunchAgent: the agent starts one at login, and the user then
    double-clicks `ImageView.app` — which is the *documented* way to
    launch it — producing a second identical status item with no way to
    tell the two apart, and two processes writing `command.json`.

    Exit **0** on contention, the same as the display's guard and for
    the same reason: `KeepAlive {SuccessfulExit: false}` does not
    respawn a clean exit, so the loser stays down instead of
    respawn-looping against the winner.

    🔵 **Rewritten 2026-09-10 — this docstring described the opposite of
    what the function now does.** It said "nothing visible happens when
    the user double-clicks an already-running ImageView", that "the honest
    fix is not an alert", that a fix "needs a channel between the two UI
    processes, which does not exist yet", and that nothing visible to the
    user had changed — while pointing at a rough-edge section of
    `ui/README.md` that the same change deleted. Every sentence was true
    when it was written and false by the time anyone read it. Nothing can
    fail on a docstring, which is exactly why it is worth saying: **when a
    phase changes what a code path is, grep the prose describing what it
    used to be.**

    **A contended launch is no longer silent, and needed no channel.** The
    arriving instance asks the window server what the holder has on
    screen, reads its heartbeat and probes its state directory — all from
    outside, with no cooperation from the holder and no TCC grant — and
    then shows a non-modal `NSPanel` placed directly under the holder's
    menu bar icon saying which of eight situations it found.
    `ui/contention.py` gathers, `ui/contention_state.py` decides,
    `ui/notice_window.py` draws.

    **A LaunchAgent respawn still shows nothing**, deliberately: it is
    routine housekeeping, and a window at every login would be the noise
    the old docstring was right to be wary of. Only a human launch gets a
    response.

    The exit also survives the process: the stderr redirect is taken
    before the guard runs, so the reason reaches a log even on a Finder
    launch, where it used to go to a stderr macOS discards. See
    `display/diagnostics.py`.
    """
    # Before the guard, deliberately: the guard's decision is the first
    # thing worth recording, and until this runs a Finder-launched menu
    # bar has nowhere at all to record it. Does nothing when the UI
    # LaunchAgent already pointed stderr at this file.
    stderr_log = diagnostics.redirect_stderr_to_log(paths.UI_ROLE)
    diagnostics.note(f"menubar: pid {os.getpid()} starting.")
    if stderr_log is not None:
        diagnostics.note(f"menubar: stderr redirected to {stderr_log}.")

    ui_lock = paths.ui_lock_path()
    guard = single_instance.acquire(ui_lock, "menu bar process")
    if guard.contended:
        # `read_holder_pid` was documentation-only until now. It is load
        # bearing from here: `contention.report()` takes the pid it
        # returns, verifies it by executable path, looks at what the
        # window server says that process has on screen, probes
        # `state/` for writability itself, and reads the heartbeat at a
        # threshold of its own — then says which of seven things it
        # found. It never kills, quits or takes over; the one signal it
        # can send is SIGUSR1, behind a precondition, because an About
        # box was measured freezing this app's heartbeat for 51.2s and
        # a stale stamp is therefore a superset of "wedged".
        #
        # It never raises, so nothing here can turn a correct silent
        # exit into a traceback and a non-zero exit code — which
        # `KeepAlive {SuccessfulExit: false}` would respawn.
        #
        # Phase 4b puts the `Notice` on screen, in a non-modal `NSPanel`
        # placed directly under the holder's menu bar icon. It renders
        # what `observe()` decided and decides nothing itself — and it
        # makes none of `runModal()`, `activateIgnoringOtherApps_` or
        # `statusItemWithLength_`, because the process arriving to
        # diagnose a wedge must not make the call it is diagnosing.
        #
        # `show()` blocks until the user dismisses the window (or, for the
        # one benign "already running, here is your icon" verdict, until
        # it dismisses itself). That is deliberate: this process holds no
        # lock — losing it is why it is here — so waiting costs nothing,
        # and an instruction that vanishes before it is read is worse than
        # silence. An agent respawn gets `notice is None` and never waits.
        #
        # 🔴 Wrapped even though `observe()` and `show()` are both
        # documented never to raise, and the belt is not redundant: the
        # **arguments** are evaluated
        # out here, and `paths.lock_path()` / `ui_status_path()` /
        # `state_dir()` all go through `Path.home()`, which raises
        # `RuntimeError` when a home directory cannot be resolved. That
        # is the same hazard `pollTick_` names one level down, and here
        # it would cost a non-zero exit and the respawn loop.
        try:
            found = contention.observe(
                ui_lock,
                paths.lock_path(),
                paths.ui_status_path(),
                paths.state_dir(),
                paths.UI_AGENT_LABEL,
            )
            if found.notice is not None:
                notice_window.show(found.notice, found.icons, found.avoid)
        except Exception:
            print(
                f"menubar: the contention report itself failed; exiting 0 "
                f"anyway:\n{traceback.format_exc()}",
                file=sys.stderr,
            )
        diagnostics.note(
            f"menubar: exiting 0 deliberately — another menu bar holds "
            f"{ui_lock}. A clean exit is not respawned by "
            f"KeepAlive{{SuccessfulExit: false}}."
        )
        return 0

    if guard.unguarded:
        # Said plainly, which is the whole point of `acquire()` growing a
        # third outcome. Until it did, this state was indistinguishable
        # from a clean start and the line below could not be written —
        # `main()` could only describe the gap in a comment.
        diagnostics.note(
            f"menubar: running WITHOUT the single-instance guard — {ui_lock} "
            f"could not be created. A second menu bar is not excluded, and "
            f"ui.stacks.log will not be rotated on this launch."
        )

    # Only now, holding the lock, is this process entitled to rotate
    # `ui.stacks.log` — and arming rotates it. See the rotation rule in
    # `diagnostics.py`.
    #
    # 🔵 The gap that rule used to name is closed rather than accepted.
    # `acquire()` also returns a usable result from its `_no_guard()`
    # sentinel, when the lock file could not be created at all, and no
    # caller could previously tell the two apart — so a second unguarded
    # instance would zero a running instance's accumulated dumps.
    # `sole_writer=guard.acquired` arms without rotating in exactly that
    # case.
    stacks_log = diagnostics.arm_stack_dumps(
        paths.UI_ROLE, sole_writer=guard.acquired
    )
    if stacks_log is not None:
        diagnostics.note(
            f"menubar: kill -USR1 {os.getpid()} dumps all thread stacks "
            f"to {stacks_log}."
        )

    app = AppKit.NSApplication.sharedApplication()
    # No Dock icon, no menu bar menus -- this app *is* a status item.
    # The packaged build sets LSUIElement in Info.plist too: the
    # plist is consulted before main() runs, so setting it only here
    # lets a Dock icon flash at launch.
    app.setActivationPolicy_(AppKit.NSApplicationActivationPolicyAccessory)

    controller = MenuBarController.alloc().init()
    controller.start()
    # Held on the app object: NSStatusItem does not retain its target,
    # and a controller collected out from under the timer takes the menu
    # with it.
    app.setDelegate_(controller)
    print("menubar: running.", file=sys.stderr)
    app.run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
